// export const teams = {
//   ARI: { city: "Arizona", name: "Cardinals", logo: "https://sleepercdn.com/images/team_logos/nfl/ari.png" },
//   ATL: { city: "Atlanta", name: "Falcons", logo: "https://sleepercdn.com/images/team_logos/nfl/atl.png" },
//   BAL: { city: "Baltimore", name: "Ravens", logo: "https://sleepercdn.com/images/team_logos/nfl/bal.png" },
//   BUF: { city: "Buffalo", name: "Bills", logo: "https://sleepercdn.com/images/team_logos/nfl/buf.png" },
//   CAR: { city: "Carolina", name: "Panthers", logo: "https://sleepercdn.com/images/team_logos/nfl/car.png" },
//   CHI: { city: "Chicago", name: "Bears", logo: "https://sleepercdn.com/images/team_logos/nfl/chi.png" },
//   CIN: { city: "Cincinnati", name: "Bengals", logo: "https://sleepercdn.com/images/team_logos/nfl/cin.png" },
//   CLE: { city: "Cleveland", name: "Browns", logo: "https://sleepercdn.com/images/team_logos/nfl/cle.png" },
//   DAL: { city: "Dallas", name: "Cowboys", logo: "https://sleepercdn.com/images/team_logos/nfl/dal.png" },
//   DEN: { city: "Denver", name: "Broncos", logo: "https://sleepercdn.com/images/team_logos/nfl/den.png" },
//   DET: { city: "Detroit", name: "Lions", logo: "https://sleepercdn.com/images/team_logos/nfl/det.png" },
//   GB:  { city: "Green Bay", name: "Packers", logo: "https://sleepercdn.com/images/team_logos/nfl/gb.png" },
//   HOU: { city: "Houston", name: "Texans", logo: "https://sleepercdn.com/images/team_logos/nfl/hou.png" },
//   IND: { city: "Indianapolis", name: "Colts", logo: "https://sleepercdn.com/images/team_logos/nfl/ind.png" },
//   JAX: { city: "Jacksonville", name: "Jaguars", logo: "https://sleepercdn.com/images/team_logos/nfl/jax.png" },
//   KC:  { city: "Kansas City", name: "Chiefs", logo: "https://sleepercdn.com/images/team_logos/nfl/kc.png" },
//   MIA: { city: "Miami", name: "Dolphins", logo: "https://sleepercdn.com/images/team_logos/nfl/mia.png" },
//   MIN: { city: "Minnesota", name: "Vikings", logo: "https://sleepercdn.com/images/team_logos/nfl/min.png" },
//   NE:  { city: "New England", name: "Patriots", logo: "https://sleepercdn.com/images/team_logos/nfl/ne.png" },
//   NO:  { city: "New Orleans", name: "Saints", logo: "https://sleepercdn.com/images/team_logos/nfl/no.png" },
//   NYG: { city: "New York", name: "Giants", logo: "https://sleepercdn.com/images/team_logos/nfl/nyg.png" },
//   NYJ: { city: "New York", name: "Jets", logo: "https://sleepercdn.com/images/team_logos/nfl/nyj.png" },
//   LV:  { city: "Las Vegas", name: "Raiders", logo: "https://sleepercdn.com/images/team_logos/nfl/lv.png" },
//   PHI: { city: "Philadelphia", name: "Eagles", logo: "https://sleepercdn.com/images/team_logos/nfl/phi.png" },
//   PIT: { city: "Pittsburgh", name: "Steelers", logo: "https://sleepercdn.com/images/team_logos/nfl/pit.png" },
//   LAC: { city: "Los Angeles", name: "Chargers", logo: "https://sleepercdn.com/images/team_logos/nfl/lac.png" },
//   SF:  { city: "San Francisco", name: "49ers", logo: "https://sleepercdn.com/images/team_logos/nfl/sf.png" },
//   SEA: { city: "Seattle", name: "Seahawks", logo: "https://sleepercdn.com/images/team_logos/nfl/sea.png" },
//   LA:  { city: "Los Angeles", name: "Rams", logo: "https://sleepercdn.com/images/team_logos/nfl/lar.png" },
//   TB:  { city: "Tampa Bay", name: "Buccaneers", logo: "https://sleepercdn.com/images/team_logos/nfl/tb.png" },
//   TEN: { city: "Tennessee", name: "Titans", logo: "https://sleepercdn.com/images/team_logos/nfl/ten.png" },
//   WAS: { city: "Washington", name: "Commanders", logo: "https://sleepercdn.com/images/team_logos/nfl/was.png" }
// };

export const teams = [
  { id: "atl", city: "Atlanta", name: "Falcons", logo: "https://sleepercdn.com/images/team_logos/nfl/atl.png" },
  { id: "bal", city: "Baltimore", name: "Ravens", logo: "https://sleepercdn.com/images/team_logos/nfl/bal.png" },
  { id: "ari", city: "Arizona", name: "Cardinals", logo: "https://sleepercdn.com/images/team_logos/nfl/ari.png" },
  { id: "buf", city: "Buffalo", name: "Bills", logo: "https://sleepercdn.com/images/team_logos/nfl/buf.png" },
  { id: "car", city: "Carolina", name: "Panthers", logo: "https://sleepercdn.com/images/team_logos/nfl/car.png" },
  { id: "chi", city: "Chicago", name: "Bears", logo: "https://sleepercdn.com/images/team_logos/nfl/chi.png" },
  { id: "cin", city: "Cincinnati", name: "Bengals", logo: "https://sleepercdn.com/images/team_logos/nfl/cin.png" },
  { id: "cle", city: "Cleveland", name: "Browns", logo: "https://sleepercdn.com/images/team_logos/nfl/cle.png" },
  { id: "dal", city: "Dallas", name: "Cowboys", logo: "https://sleepercdn.com/images/team_logos/nfl/dal.png" },
  { id: "den", city: "Denver", name: "Broncos", logo: "https://sleepercdn.com/images/team_logos/nfl/den.png" },
  { id: "det", city: "Detroit", name: "Lions", logo: "https://sleepercdn.com/images/team_logos/nfl/det.png" },
  { id: "gb", city: "Green Bay", name: "Packers", logo: "https://sleepercdn.com/images/team_logos/nfl/gb.png" },
  { id: "hou", city: "Houston", name: "Texans", logo: "https://sleepercdn.com/images/team_logos/nfl/hou.png" },
  { id: "ind", city: "Indianapolis", name: "Colts", logo: "https://sleepercdn.com/images/team_logos/nfl/ind.png" },
  { id: "jax", city: "Jacksonville", name: "Jaguars", logo: "https://sleepercdn.com/images/team_logos/nfl/jax.png" },
  { id: "kc", city: "Kansas City", name: "Chiefs", logo: "https://sleepercdn.com/images/team_logos/nfl/kc.png" },
  { id: "mia", city: "Miami", name: "Dolphins", logo: "https://sleepercdn.com/images/team_logos/nfl/mia.png" },
  { id: "min", city: "Minnesota", name: "Vikings", logo: "https://sleepercdn.com/images/team_logos/nfl/min.png" },
  { id: "ne", city: "New England", name: "Patriots", logo: "https://sleepercdn.com/images/team_logos/nfl/ne.png" },
  { id: "no", city: "New Orleans", name: "Saints", logo: "https://sleepercdn.com/images/team_logos/nfl/no.png" },
  { id: "nyg", city: "New York", name: "Giants", logo: "https://sleepercdn.com/images/team_logos/nfl/nyg.png" },
  { id: "nyj", city: "New York", name: "Jets", logo: "https://sleepercdn.com/images/team_logos/nfl/nyj.png" },
  { id: "lv", city: "Las Vegas", name: "Raiders", logo: "https://sleepercdn.com/images/team_logos/nfl/lv.png" },
  { id: "phi", city: "Philadelphia", name: "Eagles", logo: "https://sleepercdn.com/images/team_logos/nfl/phi.png" },
  { id: "pit", city: "Pittsburgh", name: "Steelers", logo: "https://sleepercdn.com/images/team_logos/nfl/pit.png" },
  { id: "lac", city: "Los Angeles", name: "Chargers", logo: "https://sleepercdn.com/images/team_logos/nfl/lac.png" },
  { id: "sf", city: "San Francisco", name: "49ers", logo: "https://sleepercdn.com/images/team_logos/nfl/sf.png" },
  { id: "sea", city: "Seattle", name: "Seahawks", logo: "https://sleepercdn.com/images/team_logos/nfl/sea.png" },
  { id: "lar", city: "Los Angeles", name: "Rams", logo: "https://sleepercdn.com/images/team_logos/nfl/lar.png" },
  { id: "tb", city: "Tampa Bay", name: "Buccaneers", logo: "https://sleepercdn.com/images/team_logos/nfl/tb.png" },
  { id: "ten", city: "Tennessee", name: "Titans", logo: "https://sleepercdn.com/images/team_logos/nfl/ten.png" },
  { id: "was", city: "Washington", name: "Commanders", logo: "https://sleepercdn.com/images/team_logos/nfl/was.png" }
];
